CREATE TABLE [dbo].[Vocabulary] (
    [VocabularyId]		 INT              IDENTITY (1, 1) NOT NULL,
	[UserId]	 INT			  NOT NULL,
	[Word]					  NVARCHAR(250) NOT NULL,
	[PartOfSpeech]					  NVARCHAR(250),
	[Etymology]					  NVARCHAR(250),
	[Connotation]					  NVARCHAR(250),
	[FriendlyDefinition]					  NVARCHAR(MAX),
	[Adjective]					  NVARCHAR(250),
	[NounSingular]					  NVARCHAR(250),
	[NounPlural]					  NVARCHAR(250),
	[VerbTenseTypeId]					  INT,
	[VerbTenseI]					  NVARCHAR(250),
	[VerbTenseWe]					  NVARCHAR(250),
	[VerbTenseYou]					  NVARCHAR(250),
	[VerbTenseYou2]					  NVARCHAR(250),
	[VerbTenseHeSheIt]					  NVARCHAR(250),
	[VerbTenseThey]					  NVARCHAR(250),
	[Synonym]					  NVARCHAR(250),
	[Antonym]					  NVARCHAR(250),
	[Sentance]					  NVARCHAR(MAX),
	[Analogy]					  NVARCHAR(MAX),
    [IsActive]           BIT              NOT NULL,
    [CreateDate]         DATE             NOT NULL,
    [CreateBy]           NVARCHAR (50)    NOT NULL,
    [ChangeDate]         DATE             NOT NULL,
    [ChangeBy]           NVARCHAR (50)    NOT NULL,
    PRIMARY KEY CLUSTERED ([VocabularyId] ASC),
	CONSTRAINT [FK_dbo.Vocabulary_dbo.VerbTenseTypeVerbTenseTypeId] FOREIGN KEY ([VerbTenseTypeId]) REFERENCES [dbo].[VerbTenseType] ([VerbTenseTypeId]),
	CONSTRAINT [FK_dbo.Vocabulary_dbo.UserUserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[User] ([UserId])
);

